name: build .deb (arm64/x64)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [ x64, arm64 ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci

      - name: Build for ${{ matrix.arch }}
        run: npx electron-forge make --arch=${{ matrix.arch }}

      - uses: actions/upload-artifact@v4
        with:
          name: electron-app-${{ matrix.arch }}
          path: |
            out/make/deb/**/*.deb